apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-local
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-postgres-local
subsets:
  - addresses:
      - ip: {{ .Values.pg.host }}
    ports:
      - port: 5432