apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: simple_app_for_kube:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 11101
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: simple-app
  ports:
    - port: 11101
      targetPort: 11101
      nodePort: 30001