# Default values for simplechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: simple_app_for_kube:v1.0.0
  pullPolicy: Never

deployment:
  container:
    port: 11101

service:
  port: 11101
  nodePort: 30001

pg:
  host: 172.18.0.3

